language: minimal
dist: bionic
before_install:
  - echo "### Decrypt service account key"
  - openssl aes-256-cbc -K $encrypted_952741eb91b6_key -iv $encrypted_952741eb91b6_iv -in red-forklift-301112-beb3e4b8997c.json.enc -out red-forklift-301112-beb3e4b8997c.json -d
  - echo "### Install Google Cloud SDK"
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - sudo apt-get install apt-transport-https ca-certificates gnupg
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  - sudo apt-get update && sudo apt-get install google-cloud-sdk
  - echo "### Authenticate service account"
  - gcloud auth activate-service-account travis@red-forklift-301112.iam.gserviceaccount.com --key-file=red-forklift-301112-beb3e4b8997c.json
install: true
script: true

