apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: not-found-percentage
spec:
  args:
  - name: service-name
  metrics:
  - name: not-found-percentage
    successCondition: result[0] <= 0.10
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          avg(rate(app_not_founds_total{kubernetes_namespace="default", kubernetes_name="{{args.service-name}}"}[5m])) /
          (avg(rate(app_requests_total{kubernetes_namespace="default", kubernetes_name="{{args.service-name}}"}[5m])) > 0) or
          avg(rate(app_requests_total{kubernetes_namespace="default", kubernetes_name="{{args.service-name}}"}[5m]))

