apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: not-found-percentage
spec:
  args:
  - name: service-name
  metrics:
  - name: not-found-percentage
    interval: 5m
    successCondition: result[0] <= 0.10
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.monitoring:9090
        query: |
          avg(rate(app_1_not_founds_total{kubernetes_namespace="default", kubernetes_name="app-1"}[5m])) /
          avg(rate(app_1_requests_total{kubernetes_namespace="default", kubernetes_name="app-1"}[5m])) > 0 or
          avg(rate(app_1_requests_total{kubernetes_namespace="default", kubernetes_name="app-1"}[5m]))

