apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: app-1
  strategy:
    canary:
      analysis:
        templates:
        - templateName: not-found-percentage
        startingStep: 2
        args:
        - name: service-name
          value: app-1
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: node
        image: sckmkny/app-1:0.2.1
        ports:
        - name: node
          containerPort: 3000

