apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-1-canary
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: node
        image: sckmkny/app-1:0.3.1
        ports:
        - name: node
          containerPort: 3000

